# Generated by Django 5.1.7 on 2025-04-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('nombre_de_usuario', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('correo_electronico', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
